# Generated by Django 4.0.6 on 2022-08-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mahsol', models.IntegerField()),
                ('delete', models.BooleanField(default=False, verbose_name='حذف از سبد خرید')),
            ],
        ),
    ]
