# Generated by Django 4.0.6 on 2022-08-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
    ]
